---
driver:
  name: vagrant
  require_chef_omnibus: 12.10.24

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: centos-6.7
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[threatstack]
    provisioner:
      encrypted_data_bag_secret_key_path: test/integration/data_bags/insecure_data_bag_secret
    attributes:
      apt:
        compile_time_update: true
      threatstack:
        deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : nil %>
        feature_plan: <%= ENV['TS_FEATURE_PLAN'] != nil ? ENV['TS_FEATURE_PLAN'] : 'monitor' %>
        agent_config_args:
          - <%= ENV['TS_CONFIG_ARGS'] %>
        version: <%= ENV['TS_PACKAGE_VERSION'] %>
        cloudsight_service_action: <%= ENV['TS_SERVICE_ACTION'] != nil ? ENV['TS_SERVICE_ACTION'] : 'enable' %>
        configure_agent: <%= ENV['TS_CONFIG_AGENT'] == '0' ? false : true %>
