---
driver:
  name: vagrant
  require_chef_omnibus: 12.6.0

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: centos-6.7
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[threatstack]
    attributes:
      apt:
        compile_time_update: true
      threatstack:
        deploy_key: <%= ENV['TS_DEPLOY_KEY'] %>
