AllCops:
  Exclude:
    - metadata.rb
    - Rakefile
    - vendor/**/*
    - spec/**/*
    - Gemfile

Style/ConditionalAssignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
